---
- name: install vault
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/stevendborrelli/rpm/vault-0.1.0-1.el7.centos.x86_64.rpm"
    state: present
  tags:
    - vault
    - bootstrap

- name: configure vault service
  sudo: yes
  copy:
    src: vault.service
    dest: /usr/lib/systemd/system/vault.service
  notify:
    - restart vault
  tags:
    - vault

- name: create vault directories
  sudo: yes
  file:
    path: /etc/vault
    state: directory
  tags:
    - vault

- name: configure vault
  sudo: yes
  template:
    src: vault.config.j2
    dest: /etc/vault/vault.config
  tags:
    - vault

- name: create consul acl for vault
  run_once: yes
  sudo: yes
  command: "curl -X PUT -d '{ \"ID\": \"{{ consul_acl_vault_token }}\", \"Name\": \"vault_acl\", \"Type\": \"client\", \"Rules\": \"key \\\"vault\\\" { policy = \\\"write\\\" }\"}' http://localhost:8500/v1/acl/create?token={{ consul_acl_master_token }}"
  tags:
    - vault

- name: enable vault
  sudo: yes
  service:
    name: vault
    enabled: yes
    state: started
  tags:
    - vault

- name: wait for vault port
  wait_for:
    port: 8200
  tags:
    - vault

- include: bootstrap.yml
