---
# Workaround for https://github.com/CiscoCloud/microservices-infrastructure/issues/161 
- name: install latest device-mapper-libs
  sudo: yes
  yum:
    name: device-mapper-libs
    state: latest
  tags:
    - docker
    - bootstrap

- name: install docker
  sudo: yes
  yum:
    name: https://get.docker.com/rpm/1.7.1/centos-7/RPMS/x86_64/docker-engine-1.7.1-1.el7.centos.x86_64.rpm
    state: present
  tags:
    - docker
    - bootstrap

- name: configure docker consul dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker-network
    regexp: ^DOCKER_NETWORK_OPTIONS
    line: DOCKER_NETWORK_OPTIONS='--dns {{ ansible_default_ipv4.address }} --dns-search service.{{ consul_dns_domain }}'
    state: present
  notify:
    - restart docker
  tags:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap

- include: collectd.yml 
